-- Coffee Record: user-scoped tables + RLS (run in Supabase SQL Editor or supabase db push)

CREATE TABLE public.brew_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  date text NOT NULL,
  bean_name text NOT NULL DEFAULT '未入力',
  origins jsonb,
  origin_country text NOT NULL DEFAULT 'Unknown',
  method text NOT NULL DEFAULT 'ハンドドリップ',
  equipment_name text,
  roast_level text NOT NULL DEFAULT '中煎り',
  roastery text NOT NULL DEFAULT '未入力',
  overall_rating smallint NOT NULL DEFAULT 4,
  food_pairing text,
  filter_rinse boolean NOT NULL DEFAULT false,
  rdt_done boolean NOT NULL DEFAULT false,
  flavors jsonb NOT NULL DEFAULT '[]'::jsonb,
  aftertaste text NOT NULL DEFAULT '',
  memo text NOT NULL DEFAULT '',
  cafe_lat double precision,
  cafe_lng double precision,
  brew_photo_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX brew_logs_user_date_id_idx ON public.brew_logs (user_id, date DESC, id DESC);

ALTER TABLE public.brew_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "brew_logs_select_own" ON public.brew_logs FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "brew_logs_insert_own" ON public.brew_logs FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "brew_logs_update_own" ON public.brew_logs FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "brew_logs_delete_own" ON public.brew_logs FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

CREATE TABLE public.cafe_records (
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  id bigint NOT NULL,
  brew_log_id bigint REFERENCES public.brew_logs (id) ON DELETE CASCADE,
  cafe_name text NOT NULL,
  lat double precision NOT NULL,
  lng double precision NOT NULL,
  date text NOT NULL,
  rating smallint NOT NULL DEFAULT 4,
  bean text NOT NULL DEFAULT '未入力',
  note text NOT NULL DEFAULT '',
  food_pairing text,
  photo_url text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, id)
);

CREATE INDEX cafe_records_user_idx ON public.cafe_records (user_id);
CREATE INDEX cafe_records_brew_log_idx ON public.cafe_records (brew_log_id);

ALTER TABLE public.cafe_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "cafe_records_select_own" ON public.cafe_records FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "cafe_records_insert_own" ON public.cafe_records FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "cafe_records_update_own" ON public.cafe_records FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "cafe_records_delete_own" ON public.cafe_records FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

CREATE TABLE public.user_origin_extras (
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  country_value text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, country_value)
);

ALTER TABLE public.user_origin_extras ENABLE ROW LEVEL SECURITY;

CREATE POLICY "origin_extras_select_own" ON public.user_origin_extras FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "origin_extras_insert_own" ON public.user_origin_extras FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- upsert の ON CONFLICT DO UPDATE で必要
CREATE POLICY "origin_extras_update_own" ON public.user_origin_extras FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "origin_extras_delete_own" ON public.user_origin_extras FOR DELETE TO authenticated
  USING (auth.uid() = user_id);
